# -*- coding: utf-8 -*-
"""Debika.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/158sZZ8NAwD5xaR5Nb8U3J7i283QEQqe1
"""

from sklearn.datasets import load_breast_cancer

# Load the breast cancer dataset
data = load_breast_cancer()
X, y = data.data, data.target

from sklearn.linear_model import LogisticRegression
import joblib

# Create and train the model
model = LogisticRegression()
model.fit(X, y)

# Save the model to a file
model_filename = 'breast_cancer_model.pkl'
joblib.dump(model, model_filename)

import zipfile

# Create a zip file containing the model
with zipfile.ZipFile('model_package.zip', 'w') as z:
    z.write(model_filename)



import boto3

# Replace with your AWS credentials and region
aws_access_key = 'AKIAZARZJB4P7S5YKQHI'
aws_secret_key = 'bxLuQwC8s9U6mhrRgWZ++C18XeCE1arZJV4hYSTq'
region_name = 'eu-west-2'
bucket_name = 'debikam'
model_name = 'breast-cancer-model'
endpoint_name = 'breast-cancer-endpoint'

# Upload the model package to S3
s3_client = boto3.client('s3', aws_access_key_id=aws_access_key, aws_secret_access_key=aws_secret_key, region_name=region_name)
s3_client.upload_file('model_package.zip', bucket_name, 'model_package.zip')

# Create a SageMaker model
sagemaker_client = boto3.client('sagemaker', aws_access_key_id=aws_access_key, aws_secret_access_key=aws_secret_key, region_name=region_name)
model_response = sagemaker_client.create_model(
    ModelName=model_name,
    ExecutionRoleArn='arn:aws:iam::619669163807:role/debikaR',
    PrimaryContainer={
        'Image': 'http://acs.amazonaws.com/groups/global/AllUsers',  # Replace with the container image URL
        'ModelDataUrl': f's3://{bucket_name}/model_package.zip'
    }
)

# Create an endpoint configuration
endpoint_config_response = sagemaker_client.create_endpoint_config(
    EndpointConfigName='breast-cancer-endpoint-config',
    ProductionVariants=[
        {
            'VariantName': 'AllTraffic',
            'ModelName': model_name,
            'InitialInstanceCount': 1,
            'InstanceType': 'ml.t2.medium'  # Replace with the desired instance type
        },
    ]
)

# Create the endpoint
endpoint_response = sagemaker_client.create_endpoint(
    EndpointName=endpoint_name,
    EndpointConfigName='breast-cancer-endpoint-config',
)